/* Command */
export enum CommandCode {
  CMD_CHECK = 0,
  CMD_EMERGENCY_STOP = 1,
  CMD_RESET_ROBOT = 2,
  CMD_SET_SERVO = 3,
  CMD_SET_BRAKE = 4,
  CMD_STOP = 5,
  CMD_MOVE = 6,
  CMD_MOVE_HOME = 7,
  CMD_MOVE_ZERO = 8,
  CMD_JOINT_MOVE_TO = 9,
  CMD_JOINT_MOVE_BY = 10,
  CMD_TASK_MOVE_TO = 11,
  CMD_TASK_MOVE_BY = 12,

  CMD_START_CURRENT_PROGRAM = 14,
  CMD_PAUSE_CURRENT_PROGRAM = 15,
  CMD_RESUME_CURRENT_PROGRAM = 16,
  CMD_STOP_CURRENT_PROGRAM = 17,
  CMD_START_DEFAULT_PROGRAM = 18,
  CMD_REGISTER_DEFAULT_PROGRAM_IDX = 19,
  CMD_GET_REGISTERED_DEFAULT_PROGRAM_IDX = 20,

  CMD_IS_ROBOT_RUNNING = 30,
  CMD_IS_READY = 31,
  CMD_IS_EMG = 32,
  CMD_IS_COLLIDED = 33,
  CMD_IS_ERR = 34,
  CMD_IS_BUSY = 35,
  CMD_IS_MOVE_FINISEHD = 36,
  CMD_IS_HOME = 37,
  CMD_IS_ZERO = 38,
  CMD_IS_IN_RESETTING = 39,
  CMD_IS_DIRECT_TECAHING = 60,
  CMD_IS_TEACHING = 61,
  CMD_IS_PROGRAM_RUNNING = 62,
  CMD_IS_PROGRAM_PAUSED = 63,
  CMD_IS_CONTY_CONNECTED = 64,

  CMD_CHANGE_DIRECT_TEACHING = 80,
  CMD_FINISH_DIRECT_TEACHING = 81,

  CMD_JOINT_PUSH_BACK_WAYPOINT_SET = 90,
  CMD_JOINT_POP_BACK_WAYPOINT_SET = 91,
  CMD_JOINT_CLEAR_WAYPOINT_SET = 92,
  CMD_JOINT_EXECUTE_WAYPOINT_SET = 94,
  CMD_TASK_PUSH_BACK_WAYPOINT_SET = 95,
  CMD_TASK_POP_BACK_WAYPOINT_SET = 96,
  CMD_TASK_CLEAR_WAYPOINT_SET = 97,
  CMD_TASK_EXECUTE_WAYPOINT_SET = 99,

  CMD_SET_DEFAULT_TCP = 100,
  CMD_RESET_DEFAULT_TCP = 101,
  CMD_SET_COMP_TCP = 102,
  CMD_RESET_COMP_TCP = 103,
  CMD_SET_REFFRAME = 104,
  CMD_RESET_REFFRAME = 105,
  CMD_SET_COLLISION_LEVEL = 106,
  CMD_SET_JOINT_BOUNDARY = 107,
  CMD_SET_TASK_BOUNDARY = 108,
  CMD_SET_JOINT_WTIME = 111,
  CMD_SET_TASK_WTIME = 112,
  CMD_SET_TASK_CMODE = 113,
  CMD_SET_JOINT_BLEND_RADIUS = 116,
  CMD_SET_TASK_BLEND_RADIUS = 117,

  CMD_SET_REDUCED_MODE = 130, // not released
  CMD_SET_REDUCED_SPEED_RATIO = 131, // not released
  CMD_GET_REDUCED_MODE = 230, // not released
  CMD_GET_REDUCED_SPEED_RATIO = 231, // not released

  CMD_GET_DEFAULT_TCP = 200,
  CMD_GET_COMP_TCP = 201,
  CMD_GET_REFFRAME = 202,
  CMD_GET_COLLISION_LEVEL = 203,
  CMD_GET_JOINT_BOUNDARY = 204,
  CMD_GET_TASK_BOUNDARY = 205,
  CMD_GET_JOINT_WTIME = 208,
  CMD_GET_TASK_WTIME = 209,
  CMD_GET_TASK_CMODE = 210,
  CMD_GET_JOINT_BLEND_RADIUS = 213,
  CMD_GET_TASK_BLEND_RADIUS = 214,

  CMD_GET_RUNNING_TIME = 300,
  CMD_GET_CMODE = 301,
  CMD_GET_JOINT_STATE = 302,
  CMD_GET_JOINT_POSITION = 320,
  CMD_GET_JOINT_VELOCITY = 321,
  CMD_GET_TASK_POSITION = 322,
  CMD_GET_TASK_VELOCITY = 323,
  CMD_GET_TORQUE = 324,

  CMD_GET_LAST_EMG_INFO = 380,

  CMD_GET_SMART_DI = 400,
  CMD_GET_SMART_DIS = 401,
  CMD_SET_SMART_DO = 402,
  CMD_SET_SMART_DOS = 403,
  CMD_GET_SMART_AI = 404,
  CMD_SET_SMART_AO = 405,
  CMD_GET_SMART_DO = 406,
  CMD_GET_SMART_DOS = 407,
  CMD_GET_SMART_AO = 408,
  CMD_SET_ENDTOOL_DO = 409, // v2.3.1 added
  CMD_GET_ENDTOOL_DO = 410, // v2.3.1 added

  CMD_GET_EXTIO_FTCAN_ROBOT_RAW = 420,
  CMD_GET_EXTIO_FTCAN_ROBOT_TRANS = 421,
  CMD_GET_EXTIO_FTCAN_CB_RAW = 422,
  CMD_GET_EXTIO_FTCAN_CB_TRANS = 423,

  CMD_READ_DIRECT_VARIABLE = 460,
  CMD_READ_DIRECT_VARIABLES = 461,
  CMD_WRITE_DIRECT_VARIABLE = 462,
  CMD_WRITE_DIRECT_VARIABLES = 463,

  CMD_FOR_EXTENDED = 800,
  CMD_FOR_STREAMING = 801,

  CMD_SEND_KEYCOMMAND = 9996,
  CMD_READ_MEMORY = 9997,
  CMD_WRITE_MEMORY = 9998,
  CMD_ERROR = 9999,

  /* Extended DCP command */
  EXT_CMD_MOVE_TRAJ_BY_DATA = 1,
  EXT_CMD_MOVE_TRAJ_BY_TXT_DATA = 2,
  EXT_CMD_MOVE_TRAJ_BY_FILE = 3,
  EXT_CMD_MOVE_TRAJ_BY_TXT_FILE = 4,

  EXT_CMD_JMOVE_ABS_WAYPOINT_SET = 11,
  EXT_CMD_TMOVE_ABS_WAYPOINT_SET = 12,

  EXT_CMD_SET_JSON_PROG = 21,
  EXT_CMD_SET_JSON_PROG_START = 22
}
